SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    (SELECT MAX(ECOLI_DATA.SIZE_OF_COLONY)
     FROM ECOLI_DATA
     WHERE YEAR(DIFFERENTIATION_DATE) = YEAR
    ) - SIZE_OF_COLONY as YEAR_DEV,
    ID
FROM ECOLI_DATA
ORDER BY YEAR ASC, YEAR_DEV ASC;