-- 코드를 작성해주세요
# 물고기 종류 별 가장 큰 물고기의 ID, 물고기 이름, 길이 출력
# => FISH_TYPE 별 가장 큰 물고기의 ID, 이름

SELECT F.ID, FN.FISH_NAME, F.LENGTH 
FROM FISH_INFO AS F
JOIN FISH_NAME_INFO AS FN ON F.FISH_TYPE = FN.FISH_TYPE
# 위 테이블에 한번 더 JOIN
JOIN (SELECT FISH_TYPE, MAX(LENGTH) as LENGTH 
      FROM FISH_INFO
      GROUP BY FISH_TYPE) AS TEMP
ON F.FISH_TYPE = TEMP.FISH_TYPE AND F.LENGTH = TEMP.LENGTH 
ORDER BY F.ID ASC;
