-- 코드를 입력하세요
# '경제' 카테고리에 속하는 도서들의 BOOK_ID, AUTHOR_NAME, PUBLISHED_DATE 출력

SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d')
FROM BOOK as B
JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE B.CATEGORY = '경제'
ORDER BY B.PUBLISHED_DATE